[package]
name = "repro"
version = "0.1.0"
authors = ["Max Bruckner <max@doo.shop>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
